apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test
spec:
  secretName: test-tls
  dnsNames:
    - hello-webhook-1.kosmoz.local.gkube.eu
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: exoscale-example
