apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test
spec:
  secretName: test-tls
  dnsNames:
    - example.mycompany.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: exoscale-example
